### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by binnichtaktiv** [LeonPupier/Mensible#19]
**Describe the bug**
when I try to run 'python3 main.py' i get 
jonasb.@iMacvonJonas Mensible % python3 main.py
Traceback (most recent call last):
  File "/Users/jonasb./Downloads/Neuer Ordner/Mensible/main.py", line 2, in <module>
    from window import Window
  File "/Users/jonasb./Downloads/Neuer Ordner/Mensible/window.py", line 2, in <module>
    import os, ctypes, Pmw, customtkinter, shutil, logging
  File "/opt/homebrew/lib/python3.11/site-packages/customtkinter/__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
jonasb.@iMacvonJonas Mensible % python3 main.py
Traceback (most recent call last):
  File "/Users/jonasb./Downloads/Neuer Ordner/Mensible/main.py", line 2, in <module>
    from window import Window
  File "/Users/jonasb./Downloads/Neuer Ordner/Mensible/window.py", line 2, in <module>
    import os, ctypes, Pmw, customtkinter, shutil, logging
  File "/opt/homebrew/lib/python3.11/site-packages/customtkinter/__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
"

**To Reproduce**
idk how it happens so i cant really tell

**Expected behavior**
The program opens

**Screenshots**
![image](https://github.com/LeonPupier/Mensible/assets/96953964/9f7b9456-3a29-49cc-a01e-2d5ef69edec3)
![image](https://github.com/LeonPupier/Mensible/assets/96953964/993efe77-6769-407c-b431-1f2425a56ae6)
![image](https://github.com/LeonPupier/Mensible/assets/96953964/f464884f-fb69-4245-9dbc-6b7d47c7ebb7)

**Desktop (please complete the following information):**
macos ventura, Python 3.11.4, brew is up to date

**Additional context**

**Comment by LeonPupier** [comment]
Hey,
Excuse me for the delay in response, I was on vacation.
Regarding your problem, I think it comes from your operating system. Indeed, my software does not officially support **_MacOS_**, I have not yet been able to stabilize its development on this system.
This would explain why the dependencies fail to install...
I will try to formalize **Mensible** support on **_MacOS_** but I have no idea when it will be ready.

Thank you very much for taking the time to write this bug report it helps me a lot.
Have a nice day,
_Leon_

**Comment by binnichtaktiv** [comment]
> Hey, Excuse me for the delay in response, I was on vacation. Regarding your problem, I think it comes from your operating system. Indeed, my software does not officially support **_MacOS_**, I have not yet been able to stabilize its development on this system. This would explain why the dependencies fail to install... I will try to formalize **Mensible** support on **_MacOS_** but I have no idea when it will be ready.
> 
> Thank you very much for taking the time to write this bug report it helps me a lot. Have a nice day, _Leon_

Hi 
I figured out that I installed the wrong version. I can open the app now :) But now I just get this when I try to download a playlist. I added my api key but still that error
![image](https://github.com/LeonPupier/Mensible/assets/96953964/50487ac5-d6a7-4794-812d-d0658352a6cb)

**Comment by binnichtaktiv** [comment]
> > Hey, Excuse me for the delay in response, I was on vacation. Regarding your problem, I think it comes from your operating system. Indeed, my software does not officially support **_MacOS_**, I have not yet been able to stabilize its development on this system. This would explain why the dependencies fail to install... I will try to formalize **Mensible** support on **_MacOS_** but I have no idea when it will be ready.
> > Thank you very much for taking the time to write this bug report it helps me a lot. Have a nice day, _Leon_
> 
> Hi I figured out that I installed the wrong version. I can open the app now :) But now I just get this when I try to download a playlist. I added my api key but still that error ![image](https://user-images.githubusercontent.com/96953964/260239924-50487ac5-d6a7-4794-812d-d0658352a6cb.png)
Example link that i tried: https://open.spotify.com/playlist/6CRjwgTKmYoMEQUtFJkpLO?si=2842ffa3a4874e9b

**Comment by LeonPupier** [comment]
Hi,
I actually just tested with your playlist as an example and it doesn't work...
I'll take a look at it now, I'll let you know when I have more info.

Thank you for your help,
_Leon_

**Comment by LeonPupier** [comment]
Hey,
I come back with news!
A patch should arrive soon, I just fixed the problem. Now I have to do some deeper tests and all will be good.
Thank you for your patience and help,
_Leon_

**Comment by LeonPupier** [comment]
Hello again,
I just released patch [**1.5.5**](https://github.com/LeonPupier/Mensible/releases/tag/1.5.5) supposed to fix your problem.
Let me know if it works for you ;)
_Leon_

**Comment by binnichtaktiv** [comment]
> Hello again, I just released patch [**1.5.5**](https://github.com/LeonPupier/Mensible/releases/tag/1.5.5) supposed to fix your problem. Let me know if it works for you ;) _Leon_

Hi sorry for the late reply. Now I can click on download without errors, it says preloading tracks but then it says loading download and nothing happens🥲
It just stays there forever
![image](https://github.com/LeonPupier/Mensible/assets/96953964/95c4011d-b87b-439f-9019-b3265a4bddce)

**Comment by binnichtaktiv** [comment]
oops wrong button my bad

**Comment by LeonPupier** [comment]
Hey,
No problem, sorry to hear that, can you provide me the link of the playlist you have tested?
_Leon_

**Comment by binnichtaktiv** [comment]
I tried this one because it has fewer songs, so it's better for testing
https://open.spotify.com/playlist/0F5KXU3rvMVC2qWTaVpCwN?si=5226ec66377b4a8e

**Comment by LeonPupier** [comment]
Hooo okay, I see...
YouTube is changing things right now, I need to put exceptions on some errors.
I still have work ;)
Really sorry for the inconvenience,
_Leon_

**Comment by binnichtaktiv** [comment]
> Hooo okay, I see... YouTube is changing things right now, I need to put exceptions on some errors. I still have work ;) Really sorry for the inconvenience, _Leon_

Okay no problem I will wait😁 Let me know if you need help with testing

**Comment by LeonPupier** [comment]
Soooooo, the problem was very small !
I had to update a dependency for **YouTube** download. This being done, you can run the command again:
```shell
python3 -m pip -r requirements.txt
```
Normally after that the software should work 🤞

**Comment by LeonPupier** [comment]
(After cloning the [repository](https://github.com/LeonPupier/Mensible.git)) I will do the ***1.5.6*** release if it works for you after

**Comment by binnichtaktiv** [comment]
> repository

so now it says 100% downloaded and it created a folder but its empty 🥲
![image](https://github.com/LeonPupier/Mensible/assets/96953964/336417e0-cce4-4845-888e-b200daa92394)

**Comment by LeonPupier** [comment]
Ha...
This is due to the **MacOS** environment... I will try to fix this even if I don't have a Mac at hand

**Comment by binnichtaktiv** [comment]
> Ha... This is due to the **MacOS** environment... I will try to fix this even if I don't have a Mac at hand

Oh okay.... I will try it on my laptop in a second

**Comment by binnichtaktiv** [comment]
> Ha... This is due to the **MacOS** environment... I will try to fix this even if I don't have a Mac at hand

So I tried it on my windows laptop and it always says "Spotify API credentials are not set or valid" I even tried to 'reinstall' Mensible still the same error 😭😭

**Comment by LeonPupier** [comment]
Olala...
I develop under Linux, Windows is supposed to work however...
