### ISSUE TITLE
KeyError: 'videoDetails'

### ISSUE THREAD

**Issue by Condutiarii** [LeonPupier/Mensible#9]
I am on Windows, the application launches well, only, when I want to launch the download of a playlist I get this error:

This is a playlist on Youtube Music, the download was fine with version 1.1.

```
Exception in thread Thread-1 (search_video):
Traceback (most recent call last):
  File "C:\Users\myaccount\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\python\Mensible-1.5.0\downloader.py", line 173, in search_video
    yt.title = self.safe_title(yt)
  File "D:\app\python\Mensible-1.5.0\downloader.py", line 185, in safe_title
    safe_title = yt_obj.title
  File "C:\Users\myaccount\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=4HwmRaozkzs. Please file a bug report at https://github.com/pytube/pytube

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myaccount\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\myaccount\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\app\python\Mensible-1.5.0\downloader.py", line 177, in search_video
    logging.debug(f'Error Pytube in Playlist mode: {e}')
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by LeonPupier** [comment]
Hey !
Thank you very much for sending me the error report. Windows support for **v1.5.0** is still in testing.
In any case, the problem will be solved at the beginning of next week, I'll look into it as soon as possible :)

Have a very nice day,
_Léon_

**Comment by Condutiarii** [comment]
No problem, I'll wait and be happy to continue reporting bugs :)

**Comment by LeonPupier** [comment]
Hey :)
Can you tell me when you have time if everything works as planned?
Thanks a lot, have a nice day.
_Léon_

**Comment by Condutiarii** [comment]
Thank you @LeonPupier

I have no more errors but the download does not start. I'm investigating further as soon as possible with different playlists to see if this is the cause.

**Comment by Condutiarii** [comment]
I get an error, the target directory contains an invalid character, indeed, the title of the playlist uses a ':' and causes an error: 

```
Exception in thread Thread-2 (download_video):
Traceback (most recent call last):
  File "C:\Users\MyAccount\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\MyAccount\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MyAccount\Desktop\Mensible-1.5.1\board.py", line 235, in download_video
    os.makedirs(f'{self.software.path}/{self.playlist_title}')
  File "<frozen os>", line 225, in makedirs
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:/Users/MyAccount/Music/Mensible/Album - EVE Online: Empire Space I'
Exception in thread Thread-3 (download_video):
Traceback (most recent call last):
  File "C:\Users\MyAccount\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\MyAccount\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MyAccount\Desktop\Mensible-1.5.1\board.py", line 235, in download_video
    os.makedirs(f'{self.software.path}/{self.playlist_title}')
  File "<frozen os>", line 225, in makedirs
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:/Users/MyAccount/Music/Mensible/Album - EVE Online: Empire Space I'
```

**Comment by Condutiarii** [comment]
Ok, it's perfectly functional with a playlist whose title is without invalid characters, great news !

Thank you @LeonPupier 👍🏼

**Comment by LeonPupier** [comment]
Mmmhh, interesting...
There are sometimes differences between Windows and Linux at this level. I'll take care of it 👍

**Comment by LeonPupier** [comment]
Hey !
Indeed, while reworking the code, I had forgotten to support "forbidden" characters under *Windows*. I mainly develop under *Linux* so this little detail had escaped me _(Linux is much more permissive)_...

It's fixed, thank you very much for helping me in *Windows* support, I don't always have the time or the means to do it, but the fixes will always follow :)

*Leon*

**Comment by Condutiarii** [comment]
Leon,

I have good news, it works! 
As I develop (web) on a Windows platform while deploying on Linux, I understand very well your problem :)

Thank you for your work, I will not hesitate to come back to report bugs if others appear.

Good continuation and maybe see you soon.

**Comment by LeonPupier** [comment]
Thank you very much for your help,
I appreciate it very much.
have a great day,
Leon
